FROM node:18.18

#Fix DNS resolution
ENV NODE_OPTIONS="--dns-result-order=ipv4first"

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn install

COPY . .

RUN npx prisma generate
RUN yarn build

CMD [ "yarn", "start" ]