FROM node:18.18

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn

COPY . .

RUN npx prisma generate
RUN yarn build

CMD [ "yarn", "start" ]