export enum CREATE_CONTACT_ERRORS {
  NAME_IS_REQUIRED = "NAME_IS_REQUIRED",
  EMAIL_IS_REQUIRED = "EMAIL_IS_REQUIRED",
  EMAIL_IS_INVALID = "EMAIL_IS_INVALID",
  PHONE_IS_REQUIRED = "PHONE_IS_REQUIRED",
  PHONE_IS_INVALID = "PHONE_IS_INVALID",
}

export enum GET_CONTACT_ERRORS {
  CONTACT_NOT_FOUND = "CONTACT_NOT_FOUND",
}
